version: '3.1'

services:
  melimongo:
    image: mongo
    container_name: "melimongo"
    ports:
      - 27017:27017
  mongo-express:
    links:
      - melimongo
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_URL= "mongodb://melimongo:27017"
  operacion-fuego-quasar:
    image: operacion-fuego-quasar:1.0
    container_name: "operacion-fuego-quasar"
    ports:
      - 8090:8090
    links:
      - melimongo